version: "3.3"
services:
  web:
    build:
      context: .
    volumes:
    - .:/srv
    # - ./templates:/etc/nginx/templates
    ports:
    - "8080:80"
    environment:
    - NGINX_HOST=mytest.com
    - NGINX_PORT=80
    # command:
    # - cd ~/srv
    # - echo 'hello'
    # - bash srv/install.sh